### ISSUE TITLE
opbookmarks hangs on one of my vaults

### ISSUE THREAD

**Issue by cmer** [dteare/opbookmarks#1]
The process indefinitely hangs. After much `print` debugging, I found that the following snippet of code in `op.rs` never finishes for one of my vaults:

```rust
use std::io::Write;
item_details_cmd
    .stdin
    .as_mut()
    .expect("Child process stdin has not been captured!")
    .write_all(&json)
    .expect("Failed to write stdin");
```

**Comment by cmer** [comment]
See my branch with debugging code: https://github.com/cmer/opbookmarks/tree/debug-stall

Here's what my debug output looks like:
![CleanShot 2022-03-31 at 09 48 14@2x](https://user-images.githubusercontent.com/412/161071058-3842c18a-2a29-47ba-b03a-55c5f08cd49d.png)

**Comment by daveteare** [comment]
Thank you, Carl! This is super helpful. I had one other user report a similar problem and was going to add a verbose logging flag and I'm happy you saved me the trouble. 🙂

I'm not sure why this would be hanging in this way but it may be a moot point as version 2.0.1 of the CLI has [some improvements](https://app-updates.agilebits.com/product_history/CLI2) that will allow me to avoid this extra call entirely. I'm close to wrapping up some other projects (hence the delayed response here) and should be able to try this out next week. 

Thanks again for helping to debug this! 🤗

**Comment by cmer** [comment]
Awesome, thanks @daveteare!

**Comment by cmer** [comment]
I confirm that the latest fix did solve my issue. No more hanging!

**Comment by dteare** [comment]
Oh perfect! 🙌 Thanks for letting us know.
